/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.18 $ of : mfd-data-access.m2c,v $ 
 *
 * $Id:$
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "ctl_functions.h"

/* include our parent header */
#include "dot1dBasePortTable.h"


#include "dot1dBasePortTable_data_access.h"

/** @ingroup interface
 * @addtogroup data_access data_access: Routines to access data
 *
 * These routines are used to locate the data used to satisfy
 * requests.
 * 
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot1dBasePortTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * BRIDGE-MIB::dot1dBasePortTable is subid 4 of dot1dBase.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.17.1.4, length: 9
*/

/**
 * initialization for dot1dBasePortTable data access
 *
 * This function is called during startup to allow you to
 * allocate any resources you need for the data table.
 *
 * @param dot1dBasePortTable_reg
 *        Pointer to dot1dBasePortTable_registration
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : unrecoverable error.
 */
int dot1dBasePortTable_init_data(dot1dBasePortTable_registration *dot1dBasePortTable_reg)
{
	DEBUGMSGTL(("verbose:dot1dBasePortTable:dot1dBasePortTable_init_data","called\n"));

	/*
	 * TODO:303:o: Initialize dot1dBasePortTable data.
	 */

	return MFD_SUCCESS;
} /* dot1dBasePortTable_init_data */

/**
 * container overview
 *
 */

/**
 * container initialization
 *
 * @param container_ptr_ptr A pointer to a container pointer. If you
 *        create a custom container, use this parameter to return it
 *        to the MFD helper. If set to NULL, the MFD helper will
 *        allocate a container for you.
 * @param  cache A pointer to a cache structure. You can set the timeout
 *         and other cache flags using this pointer.
 *
 *  This function is called at startup to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases. If no custom
 *  container is allocated, the MFD code will create one for your.
 *
 *  This is also the place to set up cache behavior. The default, to
 *  simply set the cache timeout, will work well with the default
 *  container. If you are using a custom container, you may want to
 *  look at the cache helper documentation to see if there are any
 *  flags you want to set.
 *
 * @remark
 *  This would also be a good place to do any initialization needed
 *  for you data source. For example, opening a connection to another
 *  process that will supply the data, opening a database, etc.
 */
void dot1dBasePortTable_container_init(netsnmp_container **container_ptr_ptr,
                             	       netsnmp_cache *cache)
{
	DEBUGMSGTL(("verbose:dot1dBasePortTable:dot1dBasePortTable_container_init","called\n"));
    
	if (NULL == container_ptr_ptr) {
		snmp_log(LOG_ERR,"bad container param to dot1dBasePortTable_container_init\n");
		return;
	}

	/*
	 * For advanced users, you can use a custom container. If you
	 * do not create one, one will be created for you.
	 */
	*container_ptr_ptr = NULL;

	if (NULL == cache) {
		snmp_log(LOG_ERR,"bad cache param to dot1dBasePortTable_container_init\n");
		return;
	}

	/*
	 * TODO:345:A: Set up dot1dBasePortTable cache properties.
	 *
	 * Also for advanced users, you can set parameters for the
	 * cache. Do not change the magic pointer, as it is used
	 * by the MFD helper. To completely disable caching, set
	 * cache->enabled to 0.
	 */
	cache->timeout = DOT1DBASEPORTTABLE_CACHE_TIMEOUT; /* seconds */
} /* dot1dBasePortTable_container_init */

/**
 * container shutdown
 *
 * @param container_ptr A pointer to the container.
 *
 *  This function is called at shutdown to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases.
 *
 *  This function is called before dot1dBasePortTable_container_free().
 *
 * @remark
 *  This would also be a good place to do any cleanup needed
 *  for you data source. For example, closing a connection to another
 *  process that supplied the data, closing a database, etc.
 */
void dot1dBasePortTable_container_shutdown(netsnmp_container *container_ptr)
{
	DEBUGMSGTL(("verbose:dot1dBasePortTable:dot1dBasePortTable_container_shutdown","called\n"));
    
	if (NULL == container_ptr) {
		snmp_log(LOG_ERR,"bad params to dot1dBasePortTable_container_shutdown\n");
		return;
	}
} /* dot1dBasePortTable_container_shutdown */

/**
 * load initial data
 *
 * TODO:350:M: Implement dot1dBasePortTable data load
 * This function will also be called by the cache helper to load
 * the container again (after the container free function has been
 * called to free the previous contents).
 *
 * @param container container to which items should be inserted
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_RESOURCE_UNAVAILABLE : Can't access data source
 * @retval MFD_ERROR                : other error.
 *
 *  This function is called to load the index(es) (and data, optionally)
 *  for the every row in the data set.
 *
 * @remark
 *  While loading the data, the only important thing is the indexes.
 *  If access to your data is cheap/fast (e.g. you have a pointer to a
 *  structure in memory), it would make sense to update the data here.
 *  If, however, the accessing the data invovles more work (e.g. parsing
 *  some other existing data, or peforming calculations to derive the data),
 *  then you can limit yourself to setting the indexes and saving any
 *  information you will need later. Then use the saved information in
 *  dot1dBasePortTable_row_prep() for populating data.
 *
 * @note
 *  If you need consistency between rows (like you want statistics
 *  for each row to be from the same time frame), you should set all
 *  data here.
 *
 */
int dot1dBasePortTable_container_load(netsnmp_container *container)
{
	dot1dBasePortTable_rowreq_ctx *rowreq_ctx;
	size_t count = 0;
	char port[SYSFS_PATH_MAX];
	struct dirent **namelist;
	int interface_count = 0;

	snprintf(port, sizeof(port), SYSFS_CLASS_NET "/%s/brif", bridge_name);
	interface_count = scandir(port, &namelist, not_dot_dotdot, alphasort);
	if (interface_count < 0) {
		snmp_log(LOG_ERR,
			"Error getting list of all ports of bridge %s\n",
			bridge_name);
		return SNMP_ERR_GENERR;
	}

	/*
	 * temporary storage for index values
	 */
	/*
         * dot1dBasePort(1)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/R/d/h
         */
	long dot1dBasePort;


	DEBUGMSGTL(("verbose:dot1dBasePortTable:dot1dBasePortTable_container_load","called\n"));

	/*
	 * TODO:351:M: |-> Load/update data in the dot1dBasePortTable container.
	 * loop over your dot1dBasePortTable data, allocate a rowreq context,
	 * set the index(es) [and data, optionally] and insert into
	 * the container.
	 */
	for (count = 0; count < interface_count; count++) {
		/*
		 * TODO:352:M: |   |-> set indexes in new dot1dBasePortTable rowreq context.
		 * data context will be set from the param (unless NULL,
		 *      in which case a new data context will be allocated)
		 */
		rowreq_ctx = dot1dBasePortTable_allocate_rowreq_ctx(NULL);
		if (NULL == rowreq_ctx) {
			snmp_log(LOG_ERR, "memory allocation failed\n");
			return MFD_RESOURCE_UNAVAILABLE;
		}
		if(MFD_SUCCESS != 
			dot1dBasePortTable_indexes_set(rowreq_ctx, count + 1)) {
			snmp_log(LOG_ERR,"error setting index while loading "
				 "dot1dBasePortTable data.\n");
			dot1dBasePortTable_release_rowreq_ctx(rowreq_ctx);
			continue;
		}

		/*
		 * TODO:352:r: |   |-> populate dot1dBasePortTable data context.
		 * Populate data context here. (optionally, delay until row prep)
		 */
		/*
		 * TRANSIENT or semi-TRANSIENT data:
		 * copy data or save any info needed to do it in row_prep.
		 */
		/*
		 * setup/save data for dot1dBasePortIfIndex
		 * dot1dBasePortIfIndex(2)/InterfaceIndex/ASN_INTEGER/long(long)//l/A/w/e/R/d/H
		 */
		/** no mapping */
		struct sysfs_attribute *ifindex;
		unsigned long dot1dBasePortIfIndex;
		
		snprintf(port, sizeof(port), SYSFS_CLASS_NET "/%s/ifindex", namelist[count]->d_name);
		if ((ifindex = sysfs_open_attribute(port)) == NULL) {
			sysfs_close_attribute(ifindex);
			snmp_log(LOG_ERR,
				 "could not open ifindex in sysfs for bridge %s, port %s\n",
				 bridge_name, namelist[count]->d_name);
			return SNMP_ERR_GENERR;
		}

		if (sysfs_read_attribute(ifindex) == -1) {
			snmp_log(LOG_ERR,
				 "could not read ifindex in sysfs for bridge %s, port %s\n",
				 bridge_name, namelist[count]->d_name);
			return SNMP_ERR_GENERR;
		}
		
		sscanf(ifindex->value, "%u", &dot1dBasePortIfIndex);
		sysfs_close_attribute(ifindex);

		rowreq_ctx->data.dot1dBasePortIfIndex = dot1dBasePortIfIndex;
    
		/*
		 * setup/save data for dot1dBasePortCircuit
		 * dot1dBasePortCircuit(3)/OBJECTID/ASN_OBJECT_ID/oid(oid)//L/A/w/e/r/d/h
		 */
		/** no mapping */
		/*
		 * make sure there is enough space for dot1dBasePortCircuit data
		 */
		oid dot1dBasePortCircuit[] = { 0,0 };
		int dot1dBasePortCircuit_len = OID_LENGTH(dot1dBasePortCircuit); 
		if ((NULL == rowreq_ctx->data.dot1dBasePortCircuit)) {
			snmp_log(LOG_ERR,"not enough space for dot1dBasePortCircuit\n");
			return MFD_ERROR;
		}
		rowreq_ctx->data.dot1dBasePortCircuit_len = dot1dBasePortCircuit_len;
		memcpy(rowreq_ctx->data.dot1dBasePortCircuit,
		       dot1dBasePortCircuit,
		       dot1dBasePortCircuit_len);
    
		/*
		 * setup/save data for dot1dBasePortDelayExceededDiscards
		 * dot1dBasePortDelayExceededDiscards(4)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
		 */
		/** no mapping */
		rowreq_ctx->data.dot1dBasePortDelayExceededDiscards = 0;
    
		/*
		 * setup/save data for dot1dBasePortMtuExceededDiscards
		 * dot1dBasePortMtuExceededDiscards(5)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
		 */
		/** no mapping */
		struct sysfs_attribute *rx_length_errors;
		unsigned long dot1dBasePortMtuExceededDiscards;
		
		snprintf(port, sizeof(port), SYSFS_CLASS_NET "/%s/statistics/rx_length_errors", namelist[count]->d_name);
		if ((rx_length_errors = sysfs_open_attribute(port)) == NULL) {
			sysfs_close_attribute(rx_length_errors);
			snmp_log(LOG_ERR,
				 "could not open rx_length_errors in sysfs for bridge %s, port %s\n",
				 bridge_name, namelist[count]->d_name);
			return SNMP_ERR_GENERR;
		}

		if (sysfs_read_attribute(rx_length_errors) == -1) {
			snmp_log(LOG_ERR,
				 "could not read rx_length_errors in sysfs for bridge %s, port %s\n",
				 bridge_name, namelist[count]->d_name);
			return SNMP_ERR_GENERR;
		}
		
		sscanf(rx_length_errors->value, "%u", &dot1dBasePortMtuExceededDiscards);
		sysfs_close_attribute(rx_length_errors);

		rowreq_ctx->data.dot1dBasePortMtuExceededDiscards = dot1dBasePortMtuExceededDiscards;
    
        
		/*
		 * insert into table container
		 */
		CONTAINER_INSERT(container, rowreq_ctx);
	}

	DEBUGMSGT(("verbose:dot1dBasePortTable:dot1dBasePortTable_container_load", "inserted %d records\n", count));

	return MFD_SUCCESS;
} /* dot1dBasePortTable_container_load */

/**
 * container clean up
 *
 * @param container container with all current items
 *
 *  This optional callback is called prior to all
 *  item's being removed from the container. If you
 *  need to do any processing before that, do it here.
 *
 * @note
 *  The MFD helper will take care of releasing all the row contexts.
 *
 */
void
dot1dBasePortTable_container_free(netsnmp_container *container)
{
    DEBUGMSGTL(("verbose:dot1dBasePortTable:dot1dBasePortTable_container_free","called\n"));

    /*
     * TODO:380:M: Free dot1dBasePortTable container data.
     */
} /* dot1dBasePortTable_container_free */

/**
 * prepare row for processing.
 *
 *  When the agent has located the row for a request, this function is
 *  called to prepare the row for processing. If you fully populated
 *  the data context during the index setup phase, you may not need to
 *  do anything.
 *
 * @param rowreq_ctx pointer to a context.
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 */
int
dot1dBasePortTable_row_prep( dot1dBasePortTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:dot1dBasePortTable:dot1dBasePortTable_row_prep","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:390:o: Prepare row for request.
     * If populating row data was delayed, this is the place to
     * fill in the row for this request.
     */

    return MFD_SUCCESS;
} /* dot1dBasePortTable_row_prep */

/** @} */
