/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.18 $ of : mfd-data-access.m2c,v $
 *
 * $Id:$
 */
#ifndef DOT1DBASEPORTTABLE_DATA_ACCESS_H
#define DOT1DBASEPORTTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot1dBasePortTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * BRIDGE-MIB::dot1dBasePortTable is subid 4 of dot1dBase.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.17.1.4, length: 9
*/


    int dot1dBasePortTable_init_data(dot1dBasePortTable_registration * dot1dBasePortTable_reg);


    /*
     * TODO:180:o: Review dot1dBasePortTable cache timeout.
     * The number of seconds before the cache times out
     */
#define DOT1DBASEPORTTABLE_CACHE_TIMEOUT   60

void dot1dBasePortTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache);
void dot1dBasePortTable_container_shutdown(netsnmp_container *container_ptr);

int dot1dBasePortTable_container_load(netsnmp_container *container);
void dot1dBasePortTable_container_free(netsnmp_container *container);

int dot1dBasePortTable_cache_load(netsnmp_container *container);
void dot1dBasePortTable_cache_free(netsnmp_container *container);

    int dot1dBasePortTable_row_prep( dot1dBasePortTable_rowreq_ctx *rowreq_ctx);



#ifdef __cplusplus
}
#endif

#endif /* DOT1DBASEPORTTABLE_DATA_ACCESS_H */
