/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.18 $ of : mfd-data-access.m2c,v $ 
 *
 * $Id:$
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "ctl_functions.h"

/* include our parent header */
#include "dot1dStpPortTable.h"

#include "dot1dStpPortTable_data_access.h"

/** @ingroup interface
 * @addtogroup data_access data_access: Routines to access data
 *
 * These routines are used to locate the data used to satisfy
 * requests.
 * 
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot1dStpPortTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * BRIDGE-MIB::dot1dStpPortTable is subid 15 of dot1dStp.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.17.2.15, length: 9
 */

/**
 * initialization for dot1dStpPortTable data access
 *
 * This function is called during startup to allow you to
 * allocate any resources you need for the data table.
 *
 * @param dot1dStpPortTable_reg
 *        Pointer to dot1dStpPortTable_registration
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : unrecoverable error.
 */
int dot1dStpPortTable_init_data(dot1dStpPortTable_registration * dot1dStpPortTable_reg)
{
	DEBUGMSGTL(("verbose:dot1dStpPortTable:dot1dStpPortTable_init_data","called\n"));

	/*
	 * TODO:303:o: Initialize dot1dStpPortTable data.
	 */

	return MFD_SUCCESS;
} /* dot1dStpPortTable_init_data */

/**
 * container overview
 *
 */

/**
 * container initialization
 *
 * @param container_ptr_ptr A pointer to a container pointer. If you
 *        create a custom container, use this parameter to return it
 *        to the MFD helper. If set to NULL, the MFD helper will
 *        allocate a container for you.
 * @param  cache A pointer to a cache structure. You can set the timeout
 *         and other cache flags using this pointer.
 *
 *  This function is called at startup to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases. If no custom
 *  container is allocated, the MFD code will create one for your.
 *
 *  This is also the place to set up cache behavior. The default, to
 *  simply set the cache timeout, will work well with the default
 *  container. If you are using a custom container, you may want to
 *  look at the cache helper documentation to see if there are any
 *  flags you want to set.
 *
 * @remark
 *  This would also be a good place to do any initialization needed
 *  for you data source. For example, opening a connection to another
 *  process that will supply the data, opening a database, etc.
 */
void dot1dStpPortTable_container_init(netsnmp_container **container_ptr_ptr,
				      netsnmp_cache *cache)
{
	DEBUGMSGTL(("verbose:dot1dStpPortTable:dot1dStpPortTable_container_init","called\n"));
    
	if (NULL == container_ptr_ptr) {
		snmp_log(LOG_ERR,"bad container param to dot1dStpPortTable_container_init\n");
		return;
	}

	/*
	 * For advanced users, you can use a custom container. If you
	 * do not create one, one will be created for you.
	 */
	*container_ptr_ptr = NULL;

	if (NULL == cache) {
		snmp_log(LOG_ERR,"bad cache param to dot1dStpPortTable_container_init\n");
		return;
	}

	/*
	 * TODO:345:A: Set up dot1dStpPortTable cache properties.
	 *
	 * Also for advanced users, you can set parameters for the
	 * cache. Do not change the magic pointer, as it is used
	 * by the MFD helper. To completely disable caching, set
	 * cache->enabled to 0.
	 */
	cache->timeout = DOT1DSTPPORTTABLE_CACHE_TIMEOUT; /* seconds */
} /* dot1dStpPortTable_container_init */

/**
 * container shutdown
 *
 * @param container_ptr A pointer to the container.
 *
 *  This function is called at shutdown to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases.
 *
 *  This function is called before dot1dStpPortTable_container_free().
 *
 * @remark
 *  This would also be a good place to do any cleanup needed
 *  for you data source. For example, closing a connection to another
 *  process that supplied the data, closing a database, etc.
 */
void dot1dStpPortTable_container_shutdown(netsnmp_container *container_ptr)
{
	DEBUGMSGTL(("verbose:dot1dStpPortTable:dot1dStpPortTable_container_shutdown","called\n"));
    
	if (NULL == container_ptr) {
		snmp_log(LOG_ERR,"bad params to dot1dStpPortTable_container_shutdown\n");
		return;
	}

} /* dot1dStpPortTable_container_shutdown */

/**
 * load initial data
 *
 * TODO:350:M: Implement dot1dStpPortTable data load
 * This function will also be called by the cache helper to load
 * the container again (after the container free function has been
 * called to free the previous contents).
 *
 * @param container container to which items should be inserted
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_RESOURCE_UNAVAILABLE : Can't access data source
 * @retval MFD_ERROR                : other error.
 *
 *  This function is called to load the index(es) (and data, optionally)
 *  for the every row in the data set.
 *
 * @remark
 *  While loading the data, the only important thing is the indexes.
 *  If access to your data is cheap/fast (e.g. you have a pointer to a
 *  structure in memory), it would make sense to update the data here.
 *  If, however, the accessing the data invovles more work (e.g. parsing
 *  some other existing data, or peforming calculations to derive the data),
 *  then you can limit yourself to setting the indexes and saving any
 *  information you will need later. Then use the saved information in
 *  dot1dStpPortTable_row_prep() for populating data.
 *
 * @note
 *  If you need consistency between rows (like you want statistics
 *  for each row to be from the same time frame), you should set all
 *  data here.
 *
 */
int dot1dStpPortTable_container_load(netsnmp_container *container)
{
	dot1dStpPortTable_rowreq_ctx *rowreq_ctx;
	size_t count = 0;
	char port[SYSFS_PATH_MAX];
	struct dirent **namelist;
	int interface_count = 0;
	int r = 0;

	UID_STP_STATE_T uid_state;
	UID_STP_CFG_T uid_cfg;
	UID_STP_PORT_STATE_T uid_port;
	UID_STP_PORT_CFG_T uid_port_cfg;

	int br_index = get_index_die(bridge_name, "bridge", 0);
	if (br_index == SNMP_ERR_GENERR)
		return br_index;
	
	snprintf(port, sizeof(port), SYSFS_CLASS_NET "/%s/brif", bridge_name);
	interface_count = scandir(port, &namelist, not_dot_dotdot, alphasort);
	if (interface_count < 0) {
		snmp_log(LOG_ERR,
			"Error getting list of all ports of bridge %s\n",
			bridge_name);
		return SNMP_ERR_GENERR;
	}

	DEBUGMSGTL(("verbose:dot1dStpPortTable:dot1dStpPortTable_container_load","called\n"));

	/*
	 * TODO:351:M: |-> Load/update data in the dot1dStpPortTable container.
	 * loop over your dot1dStpPortTable data, allocate a rowreq context,
	 * set the index(es) [and data, optionally] and insert into
	 * the container.
	 */
	for (count = 0; count < interface_count; count++) {
		int port_index = get_index_die(namelist[count]->d_name, "port", 0);
		if (port_index < 0)
			return -1;

		memset(&uid_port_cfg, 0, sizeof(UID_STP_PORT_CFG_T));
		r = CTL_get_port_state(br_index, port_index, &uid_port_cfg, &uid_port);
		if (r) {
			fprintf(stderr, "Failed to get port state for port %d: %s\n",
				port_index, CTL_error_explanation(r));
			return -1;
		}

		/*
		 * TODO:352:M: |   |-> set indexes in new dot1dStpPortTable rowreq context.
		 * data context will be set from the param (unless NULL,
		 *      in which case a new data context will be allocated)
		 */
		rowreq_ctx = dot1dStpPortTable_allocate_rowreq_ctx(NULL);
		if (NULL == rowreq_ctx) {
			snmp_log(LOG_ERR, "memory allocation failed\n");
			return MFD_RESOURCE_UNAVAILABLE;
		}
		if (MFD_SUCCESS != dot1dStpPortTable_indexes_set(rowreq_ctx, count + 1)) {
			snmp_log(LOG_ERR,"error setting index while loading "
					 "dot1dStpPortTable data.\n");
			dot1dStpPortTable_release_rowreq_ctx(rowreq_ctx);
			continue;
		}

		/*
		 * TODO:352:r: |   |-> populate dot1dStpPortTable data context.
		 * Populate data context here. (optionally, delay until row prep)
		 */
		/*
		 * TRANSIENT or semi-TRANSIENT data:
		 * copy data or save any info needed to do it in row_prep.
		 */
		/*
		 * setup/save data for dot1dStpPortPriority
		 * dot1dStpPortPriority(2)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/R/d/h
		 */
		/** no mapping */
		rowreq_ctx->data.dot1dStpPortPriority = (long)(uid_port.port_id >> 8);
    
		/*
		 * setup/save data for dot1dStpPortState
		 * dot1dStpPortState(3)/INTEGER/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h
		 */
		/** no mapping */
		switch (uid_port.state) {
			case UID_PORT_DISABLED:
				rowreq_ctx->data.dot1dStpPortState = dot1dStpPortState_DISABLED;
			break;
			case UID_PORT_DISCARDING:
				rowreq_ctx->data.dot1dStpPortState = dot1dStpPortState_BLOCKING;
			break;
			case UID_PORT_LEARNING:
				rowreq_ctx->data.dot1dStpPortState = dot1dStpPortState_LEARNING;
			break;
			case UID_PORT_FORWARDING:
				rowreq_ctx->data.dot1dStpPortState = dot1dStpPortState_FORWARDING;
			break;
			default:
				rowreq_ctx->data.dot1dStpPortState = dot1dStpPortState_BROKEN;
			break;
		}
    
		/*
		 * setup/save data for dot1dStpPortEnable
		 * dot1dStpPortEnable(4)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h
		 */
		/** no mapping */
		rowreq_ctx->data.dot1dStpPortEnable = uid_port.state == UID_PORT_DISABLED ? dot1dStpPortEnable_DISABLED : dot1dStpPortEnable_ENABLED;
    
		/*
		 * setup/save data for dot1dStpPortPathCost
		 * dot1dStpPortPathCost(5)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/R/d/h
		 */
		/** no mapping */
		rowreq_ctx->data.dot1dStpPortPathCost = uid_port.path_cost;
    
		/*
		 * setup/save data for dot1dStpPortDesignatedRoot
		 * dot1dStpPortDesignatedRoot(6)/BridgeId/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/h
		 */
		/** no mapping */
		/*
		 * make sure there is enough space for dot1dStpPortDesignatedRoot data
		 */
		if ((NULL == rowreq_ctx->data.dot1dStpPortDesignatedRoot)) {
			snmp_log(LOG_ERR,"not enough space for dot1dStpPortDesignatedRoot\n");
			return MFD_ERROR;
		}
		rowreq_ctx->data.dot1dStpPortDesignatedRoot_len = sizeof(uid_port.designated_root);
		memcpy(rowreq_ctx->data.dot1dStpPortDesignatedRoot,
		       &uid_port.designated_root,
		       sizeof(uid_port.designated_root));
    
		/*
		 * setup/save data for dot1dStpPortDesignatedCost
		 * dot1dStpPortDesignatedCost(7)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
		 */
		/** no mapping */
		rowreq_ctx->data.dot1dStpPortDesignatedCost = uid_port.designated_cost;
    
		/*
		 * setup/save data for dot1dStpPortDesignatedBridge
		 * dot1dStpPortDesignatedBridge(8)/BridgeId/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/h
		 */
		/** no mapping */
		/*
		 * make sure there is enough space for dot1dStpPortDesignatedBridge data
		 */
		if ((NULL == rowreq_ctx->data.dot1dStpPortDesignatedBridge)) {
			snmp_log(LOG_ERR,"not enough space for dot1dStpPortDesignatedBridge\n");
			return MFD_ERROR;
		}
		rowreq_ctx->data.dot1dStpPortDesignatedBridge_len = sizeof(uid_port.designated_bridge);
		memcpy(rowreq_ctx->data.dot1dStpPortDesignatedBridge,
		       &uid_port.designated_bridge,
		       sizeof(uid_port.designated_bridge));
    
		/*
		 * setup/save data for dot1dStpPortDesignatedPort
		 * dot1dStpPortDesignatedPort(9)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/h
		 */
		/** no mapping */
		/*
		 * make sure there is enough space for dot1dStpPortDesignatedPort data
		 */
		if ((NULL == rowreq_ctx->data.dot1dStpPortDesignatedPort)) {
			snmp_log(LOG_ERR,"not enough space for dot1dStpPortDesignatedPort\n");
			return MFD_ERROR;
		}
		rowreq_ctx->data.dot1dStpPortDesignatedPort_len = sizeof(uid_port.designated_port);
		memcpy(rowreq_ctx->data.dot1dStpPortDesignatedPort,
		       &uid_port.designated_port,
		       sizeof(uid_port.designated_port));
    
		/*
		 * setup/save data for dot1dStpPortForwardTransitions
		 * dot1dStpPortForwardTransitions(10)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
		 */
		/** no mapping */
		rowreq_ctx->data.dot1dStpPortForwardTransitions = 0;
    
		/*
		 * setup/save data for dot1dStpPortPathCost32
		 * dot1dStpPortPathCost32(11)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/R/d/h
		 */
		/** no mapping */
		rowreq_ctx->data.dot1dStpPortPathCost32 = uid_port.path_cost;
    
        
		/*
		 * insert into table container
		 */
		CONTAINER_INSERT(container, rowreq_ctx);
	}

	DEBUGMSGT(("verbose:dot1dStpPortTable:dot1dStpPortTable_container_load",
		   "inserted %d records\n", count));

	return MFD_SUCCESS;
} /* dot1dStpPortTable_container_load */

/**
 * container clean up
 *
 * @param container container with all current items
 *
 *  This optional callback is called prior to all
 *  item's being removed from the container. If you
 *  need to do any processing before that, do it here.
 *
 * @note
 *  The MFD helper will take care of releasing all the row contexts.
 *
 */
void
dot1dStpPortTable_container_free(netsnmp_container *container)
{
    DEBUGMSGTL(("verbose:dot1dStpPortTable:dot1dStpPortTable_container_free","called\n"));

    /*
     * TODO:380:M: Free dot1dStpPortTable container data.
     */
} /* dot1dStpPortTable_container_free */

/**
 * prepare row for processing.
 *
 *  When the agent has located the row for a request, this function is
 *  called to prepare the row for processing. If you fully populated
 *  the data context during the index setup phase, you may not need to
 *  do anything.
 *
 * @param rowreq_ctx pointer to a context.
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 */
int
dot1dStpPortTable_row_prep( dot1dStpPortTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:dot1dStpPortTable:dot1dStpPortTable_row_prep","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:390:o: Prepare row for request.
     * If populating row data was delayed, this is the place to
     * fill in the row for this request.
     */

    return MFD_SUCCESS;
} /* dot1dStpPortTable_row_prep */

/** @} */
