/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.19 $ of : mfd-data-set.m2c,v $ 
 *
 * $Id:$
 */
#ifndef DOT1DSTPPORTTABLE_DATA_SET_H
#define DOT1DSTPPORTTABLE_DATA_SET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * SET function declarations
 */

/* *********************************************************************
 * SET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot1dStpPortTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * BRIDGE-MIB::dot1dStpPortTable is subid 15 of dot1dStp.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.17.2.15, length: 9
*/


int dot1dStpPortTable_undo_setup( dot1dStpPortTable_rowreq_ctx *rowreq_ctx);
int dot1dStpPortTable_undo_cleanup( dot1dStpPortTable_rowreq_ctx *rowreq_ctx);
int dot1dStpPortTable_undo( dot1dStpPortTable_rowreq_ctx *rowreq_ctx);
int dot1dStpPortTable_commit( dot1dStpPortTable_rowreq_ctx *rowreq_ctx);
int dot1dStpPortTable_undo_commit( dot1dStpPortTable_rowreq_ctx *rowreq_ctx);


int dot1dStpPortPriority_check_value( dot1dStpPortTable_rowreq_ctx *rowreq_ctx, long dot1dStpPortPriority_val);
int dot1dStpPortPriority_undo_setup( dot1dStpPortTable_rowreq_ctx *rowreq_ctx );
int dot1dStpPortPriority_set( dot1dStpPortTable_rowreq_ctx *rowreq_ctx, long dot1dStpPortPriority_val );
int dot1dStpPortPriority_undo( dot1dStpPortTable_rowreq_ctx *rowreq_ctx );

int dot1dStpPortState_check_value( dot1dStpPortTable_rowreq_ctx *rowreq_ctx, u_long dot1dStpPortState_val);
int dot1dStpPortState_undo_setup( dot1dStpPortTable_rowreq_ctx *rowreq_ctx );
int dot1dStpPortState_set( dot1dStpPortTable_rowreq_ctx *rowreq_ctx, u_long dot1dStpPortState_val );
int dot1dStpPortState_undo( dot1dStpPortTable_rowreq_ctx *rowreq_ctx );

int dot1dStpPortEnable_check_value( dot1dStpPortTable_rowreq_ctx *rowreq_ctx, u_long dot1dStpPortEnable_val);
int dot1dStpPortEnable_undo_setup( dot1dStpPortTable_rowreq_ctx *rowreq_ctx );
int dot1dStpPortEnable_set( dot1dStpPortTable_rowreq_ctx *rowreq_ctx, u_long dot1dStpPortEnable_val );
int dot1dStpPortEnable_undo( dot1dStpPortTable_rowreq_ctx *rowreq_ctx );

int dot1dStpPortPathCost_check_value( dot1dStpPortTable_rowreq_ctx *rowreq_ctx, long dot1dStpPortPathCost_val);
int dot1dStpPortPathCost_undo_setup( dot1dStpPortTable_rowreq_ctx *rowreq_ctx );
int dot1dStpPortPathCost_set( dot1dStpPortTable_rowreq_ctx *rowreq_ctx, long dot1dStpPortPathCost_val );
int dot1dStpPortPathCost_undo( dot1dStpPortTable_rowreq_ctx *rowreq_ctx );

int dot1dStpPortDesignatedRoot_check_value( dot1dStpPortTable_rowreq_ctx *rowreq_ctx, char *dot1dStpPortDesignatedRoot_val_ptr,  size_t dot1dStpPortDesignatedRoot_val_ptr_len);
int dot1dStpPortDesignatedRoot_undo_setup( dot1dStpPortTable_rowreq_ctx *rowreq_ctx );
int dot1dStpPortDesignatedRoot_set( dot1dStpPortTable_rowreq_ctx *rowreq_ctx, char *dot1dStpPortDesignatedRoot_val_ptr,  size_t dot1dStpPortDesignatedRoot_val_ptr_len );
int dot1dStpPortDesignatedRoot_undo( dot1dStpPortTable_rowreq_ctx *rowreq_ctx );

int dot1dStpPortDesignatedCost_check_value( dot1dStpPortTable_rowreq_ctx *rowreq_ctx, long dot1dStpPortDesignatedCost_val);
int dot1dStpPortDesignatedCost_undo_setup( dot1dStpPortTable_rowreq_ctx *rowreq_ctx );
int dot1dStpPortDesignatedCost_set( dot1dStpPortTable_rowreq_ctx *rowreq_ctx, long dot1dStpPortDesignatedCost_val );
int dot1dStpPortDesignatedCost_undo( dot1dStpPortTable_rowreq_ctx *rowreq_ctx );

int dot1dStpPortDesignatedBridge_check_value( dot1dStpPortTable_rowreq_ctx *rowreq_ctx, char *dot1dStpPortDesignatedBridge_val_ptr,  size_t dot1dStpPortDesignatedBridge_val_ptr_len);
int dot1dStpPortDesignatedBridge_undo_setup( dot1dStpPortTable_rowreq_ctx *rowreq_ctx );
int dot1dStpPortDesignatedBridge_set( dot1dStpPortTable_rowreq_ctx *rowreq_ctx, char *dot1dStpPortDesignatedBridge_val_ptr,  size_t dot1dStpPortDesignatedBridge_val_ptr_len );
int dot1dStpPortDesignatedBridge_undo( dot1dStpPortTable_rowreq_ctx *rowreq_ctx );

int dot1dStpPortDesignatedPort_check_value( dot1dStpPortTable_rowreq_ctx *rowreq_ctx, char *dot1dStpPortDesignatedPort_val_ptr,  size_t dot1dStpPortDesignatedPort_val_ptr_len);
int dot1dStpPortDesignatedPort_undo_setup( dot1dStpPortTable_rowreq_ctx *rowreq_ctx );
int dot1dStpPortDesignatedPort_set( dot1dStpPortTable_rowreq_ctx *rowreq_ctx, char *dot1dStpPortDesignatedPort_val_ptr,  size_t dot1dStpPortDesignatedPort_val_ptr_len );
int dot1dStpPortDesignatedPort_undo( dot1dStpPortTable_rowreq_ctx *rowreq_ctx );

int dot1dStpPortForwardTransitions_check_value( dot1dStpPortTable_rowreq_ctx *rowreq_ctx, u_long dot1dStpPortForwardTransitions_val);
int dot1dStpPortForwardTransitions_undo_setup( dot1dStpPortTable_rowreq_ctx *rowreq_ctx );
int dot1dStpPortForwardTransitions_set( dot1dStpPortTable_rowreq_ctx *rowreq_ctx, u_long dot1dStpPortForwardTransitions_val );
int dot1dStpPortForwardTransitions_undo( dot1dStpPortTable_rowreq_ctx *rowreq_ctx );

int dot1dStpPortPathCost32_check_value( dot1dStpPortTable_rowreq_ctx *rowreq_ctx, long dot1dStpPortPathCost32_val);
int dot1dStpPortPathCost32_undo_setup( dot1dStpPortTable_rowreq_ctx *rowreq_ctx );
int dot1dStpPortPathCost32_set( dot1dStpPortTable_rowreq_ctx *rowreq_ctx, long dot1dStpPortPathCost32_val );
int dot1dStpPortPathCost32_undo( dot1dStpPortTable_rowreq_ctx *rowreq_ctx );


int dot1dStpPortTable_check_dependencies(dot1dStpPortTable_rowreq_ctx *ctx);


#ifdef __cplusplus
}
#endif

#endif /* DOT1DSTPPORTTABLE_DATA_SET_H */
