/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.18 $ of : mfd-data-access.m2c,v $
 *
 * $Id:$
 */
#ifndef DOT1DSTPPORTTABLE_DATA_ACCESS_H
#define DOT1DSTPPORTTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot1dStpPortTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * BRIDGE-MIB::dot1dStpPortTable is subid 15 of dot1dStp.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.17.2.15, length: 9
 */

int dot1dStpPortTable_init_data(dot1dStpPortTable_registration *dot1dStpPortTable_reg);

/*
 * TODO:180:o: Review dot1dStpPortTable cache timeout.
 * The number of seconds before the cache times out
 */
#define DOT1DSTPPORTTABLE_CACHE_TIMEOUT 60

void dot1dStpPortTable_container_init(netsnmp_container **container_ptr_ptr,
				      netsnmp_cache *cache);
void dot1dStpPortTable_container_shutdown(netsnmp_container *container_ptr);

int dot1dStpPortTable_container_load(netsnmp_container *container);
void dot1dStpPortTable_container_free(netsnmp_container *container);

int dot1dStpPortTable_cache_load(netsnmp_container *container);
void dot1dStpPortTable_cache_free(netsnmp_container *container);

int dot1dStpPortTable_row_prep( dot1dStpPortTable_rowreq_ctx *rowreq_ctx);

#ifdef __cplusplus
}
#endif

#endif /* DOT1DSTPPORTTABLE_DATA_ACCESS_H */
