/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.20 $ of : mfd-data-get.m2c,v $
 *
 * $Id:$
 *
 * @file dot1dStpPortTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef DOT1DSTPPORTTABLE_DATA_GET_H
#define DOT1DSTPPORTTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot1dStpPortTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * BRIDGE-MIB::dot1dStpPortTable is subid 15 of dot1dStp.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.17.2.15, length: 9
*/
    /*
     * indexes
     */

    int dot1dStpPortPriority_get( dot1dStpPortTable_rowreq_ctx *rowreq_ctx, long * dot1dStpPortPriority_val_ptr );
    int dot1dStpPortState_get( dot1dStpPortTable_rowreq_ctx *rowreq_ctx, u_long * dot1dStpPortState_val_ptr );
    int dot1dStpPortEnable_get( dot1dStpPortTable_rowreq_ctx *rowreq_ctx, u_long * dot1dStpPortEnable_val_ptr );
    int dot1dStpPortPathCost_get( dot1dStpPortTable_rowreq_ctx *rowreq_ctx, long * dot1dStpPortPathCost_val_ptr );
    int dot1dStpPortDesignatedRoot_get( dot1dStpPortTable_rowreq_ctx *rowreq_ctx, char **dot1dStpPortDesignatedRoot_val_ptr_ptr, size_t *dot1dStpPortDesignatedRoot_val_ptr_len_ptr );
    int dot1dStpPortDesignatedCost_get( dot1dStpPortTable_rowreq_ctx *rowreq_ctx, long * dot1dStpPortDesignatedCost_val_ptr );
    int dot1dStpPortDesignatedBridge_get( dot1dStpPortTable_rowreq_ctx *rowreq_ctx, char **dot1dStpPortDesignatedBridge_val_ptr_ptr, size_t *dot1dStpPortDesignatedBridge_val_ptr_len_ptr );
    int dot1dStpPortDesignatedPort_get( dot1dStpPortTable_rowreq_ctx *rowreq_ctx, char **dot1dStpPortDesignatedPort_val_ptr_ptr, size_t *dot1dStpPortDesignatedPort_val_ptr_len_ptr );
    int dot1dStpPortForwardTransitions_get( dot1dStpPortTable_rowreq_ctx *rowreq_ctx, u_long * dot1dStpPortForwardTransitions_val_ptr );
    int dot1dStpPortPathCost32_get( dot1dStpPortTable_rowreq_ctx *rowreq_ctx, long * dot1dStpPortPathCost32_val_ptr );


int dot1dStpPortTable_indexes_set_tbl_idx(dot1dStpPortTable_mib_index *tbl_idx, long dot1dStpPort_val);
int dot1dStpPortTable_indexes_set(dot1dStpPortTable_rowreq_ctx *rowreq_ctx, long dot1dStpPort_val);




#ifdef __cplusplus
}
#endif

#endif /* DOT1DSTPPORTTABLE_DATA_GET_H */
/** @} */
