/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.19 $ of : mfd-data-set.m2c,v $ 
 *
 * $Id:$
 */
#ifndef DOT1DTPPORTTABLE_DATA_SET_H
#define DOT1DTPPORTTABLE_DATA_SET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * SET function declarations
 */

/* *********************************************************************
 * SET Table declarations
 */


#ifdef __cplusplus
}
#endif

#endif /* DOT1DTPPORTTABLE_DATA_SET_H */
