/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.18 $ of : mfd-data-access.m2c,v $ 
 *
 * $Id:$
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "ctl_functions.h"

/* include our parent header */
#include "dot1dTpPortTable.h"


#include "dot1dTpPortTable_data_access.h"

/** @ingroup interface
 * @addtogroup data_access data_access: Routines to access data
 *
 * These routines are used to locate the data used to satisfy
 * requests.
 * 
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot1dTpPortTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * BRIDGE-MIB::dot1dTpPortTable is subid 4 of dot1dTp.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.17.4.4, length: 9
*/

/**
 * initialization for dot1dTpPortTable data access
 *
 * This function is called during startup to allow you to
 * allocate any resources you need for the data table.
 *
 * @param dot1dTpPortTable_reg
 *        Pointer to dot1dTpPortTable_registration
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : unrecoverable error.
 */
int
dot1dTpPortTable_init_data(dot1dTpPortTable_registration * dot1dTpPortTable_reg)
{
    DEBUGMSGTL(("verbose:dot1dTpPortTable:dot1dTpPortTable_init_data","called\n"));

    /*
     * TODO:303:o: Initialize dot1dTpPortTable data.
     */

    return MFD_SUCCESS;
} /* dot1dTpPortTable_init_data */

/**
 * container overview
 *
 */

/**
 * container initialization
 *
 * @param container_ptr_ptr A pointer to a container pointer. If you
 *        create a custom container, use this parameter to return it
 *        to the MFD helper. If set to NULL, the MFD helper will
 *        allocate a container for you.
 * @param  cache A pointer to a cache structure. You can set the timeout
 *         and other cache flags using this pointer.
 *
 *  This function is called at startup to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases. If no custom
 *  container is allocated, the MFD code will create one for your.
 *
 *  This is also the place to set up cache behavior. The default, to
 *  simply set the cache timeout, will work well with the default
 *  container. If you are using a custom container, you may want to
 *  look at the cache helper documentation to see if there are any
 *  flags you want to set.
 *
 * @remark
 *  This would also be a good place to do any initialization needed
 *  for you data source. For example, opening a connection to another
 *  process that will supply the data, opening a database, etc.
 */
void
dot1dTpPortTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache)
{
    DEBUGMSGTL(("verbose:dot1dTpPortTable:dot1dTpPortTable_container_init","called\n"));
    
    if (NULL == container_ptr_ptr) {
        snmp_log(LOG_ERR,"bad container param to dot1dTpPortTable_container_init\n");
        return;
    }

    /*
     * For advanced users, you can use a custom container. If you
     * do not create one, one will be created for you.
     */
    *container_ptr_ptr = NULL;

    if (NULL == cache) {
        snmp_log(LOG_ERR,"bad cache param to dot1dTpPortTable_container_init\n");
        return;
    }

    /*
     * TODO:345:A: Set up dot1dTpPortTable cache properties.
     *
     * Also for advanced users, you can set parameters for the
     * cache. Do not change the magic pointer, as it is used
     * by the MFD helper. To completely disable caching, set
     * cache->enabled to 0.
     */
    cache->timeout = DOT1DTPPORTTABLE_CACHE_TIMEOUT; /* seconds */
} /* dot1dTpPortTable_container_init */

/**
 * container shutdown
 *
 * @param container_ptr A pointer to the container.
 *
 *  This function is called at shutdown to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases.
 *
 *  This function is called before dot1dTpPortTable_container_free().
 *
 * @remark
 *  This would also be a good place to do any cleanup needed
 *  for you data source. For example, closing a connection to another
 *  process that supplied the data, closing a database, etc.
 */
void
dot1dTpPortTable_container_shutdown(netsnmp_container *container_ptr)
{
    DEBUGMSGTL(("verbose:dot1dTpPortTable:dot1dTpPortTable_container_shutdown","called\n"));
    
    if (NULL == container_ptr) {
        snmp_log(LOG_ERR,"bad params to dot1dTpPortTable_container_shutdown\n");
        return;
    }

} /* dot1dTpPortTable_container_shutdown */

/**
 * load initial data
 *
 * TODO:350:M: Implement dot1dTpPortTable data load
 * This function will also be called by the cache helper to load
 * the container again (after the container free function has been
 * called to free the previous contents).
 *
 * @param container container to which items should be inserted
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_RESOURCE_UNAVAILABLE : Can't access data source
 * @retval MFD_ERROR                : other error.
 *
 *  This function is called to load the index(es) (and data, optionally)
 *  for the every row in the data set.
 *
 * @remark
 *  While loading the data, the only important thing is the indexes.
 *  If access to your data is cheap/fast (e.g. you have a pointer to a
 *  structure in memory), it would make sense to update the data here.
 *  If, however, the accessing the data invovles more work (e.g. parsing
 *  some other existing data, or peforming calculations to derive the data),
 *  then you can limit yourself to setting the indexes and saving any
 *  information you will need later. Then use the saved information in
 *  dot1dTpPortTable_row_prep() for populating data.
 *
 * @note
 *  If you need consistency between rows (like you want statistics
 *  for each row to be from the same time frame), you should set all
 *  data here.
 *
 */
int dot1dTpPortTable_container_load(netsnmp_container *container)
{
	dot1dTpPortTable_rowreq_ctx *rowreq_ctx;
	size_t count = 0;
	char port[SYSFS_PATH_MAX];
	struct dirent **namelist;
	int interface_count = 0;

	snprintf(port, sizeof(port), SYSFS_CLASS_NET "/%s/brif", bridge_name);
	interface_count = scandir(port, &namelist, not_dot_dotdot, alphasort);
	if (interface_count < 0) {
		snmp_log(LOG_ERR,
			"Error getting list of all ports of bridge %s\n",
			bridge_name);
		return SNMP_ERR_GENERR;
	}

	DEBUGMSGTL(("verbose:dot1dTpPortTable:dot1dTpPortTable_container_load","called\n"));

	/*
	 * TODO:351:M: |-> Load/update data in the dot1dTpPortTable container.
	 * loop over your dot1dTpPortTable data, allocate a rowreq context,
	 * set the index(es) [and data, optionally] and insert into
	 * the container.
	 */
	for (count = 0; count < interface_count; count++) {

		/*
		 * TODO:352:M: |   |-> set indexes in new dot1dTpPortTable rowreq context.
		 * data context will be set from the param (unless NULL,
		 * in which case a new data context will be allocated)
		 */
		rowreq_ctx = dot1dTpPortTable_allocate_rowreq_ctx(NULL);
		if (NULL == rowreq_ctx) {
			snmp_log(LOG_ERR, "memory allocation failed\n");
			return MFD_RESOURCE_UNAVAILABLE;
		}
		if (MFD_SUCCESS != dot1dTpPortTable_indexes_set(rowreq_ctx, count + 1)) {
			snmp_log(LOG_ERR,"error setting index while loading "
				 "dot1dTpPortTable data.\n");
			dot1dTpPortTable_release_rowreq_ctx(rowreq_ctx);
			continue;
		}

		/*
		 * TODO:352:r: |   |-> populate dot1dTpPortTable data context.
		 * Populate data context here. (optionally, delay until row prep)
		 */
		/*
		 * TRANSIENT or semi-TRANSIENT data:
		 * copy data or save any info needed to do it in row_prep.
		 */
		/*
		 * setup/save data for dot1dTpPortMaxInfo
		 * dot1dTpPortMaxInfo(2)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
		 */
		/** no mapping */
		struct sysfs_attribute *mtu;
		unsigned long dot1dTpPortMaxInfo;
		
		snprintf(port, sizeof(port), SYSFS_CLASS_NET "/%s/mtu", namelist[count]->d_name);
		if ((mtu = sysfs_open_attribute(port)) == NULL) {
			sysfs_close_attribute(mtu);
			snmp_log(LOG_ERR,
				 "could not open mtu in sysfs for bridge %s, port %s\n",
				 bridge_name, namelist[count]->d_name);
			return SNMP_ERR_GENERR;
		}

		if (sysfs_read_attribute(mtu) == -1) {
			snmp_log(LOG_ERR,
				 "could not read mtu in sysfs for bridge %s, port %s\n",
				 bridge_name, namelist[count]->d_name);
			return SNMP_ERR_GENERR;
		}
		
		sscanf(mtu->value, "%u", &dot1dTpPortMaxInfo);
		sysfs_close_attribute(mtu);
		rowreq_ctx->data.dot1dTpPortMaxInfo = dot1dTpPortMaxInfo + 36; // Add 36 for the ethernet preamble/postamble
    
		/*
		 * setup/save data for dot1dTpPortInFrames
		 * dot1dTpPortInFrames(3)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
		 */
		/** no mapping */
		struct sysfs_attribute *rx_packets;
		unsigned long dot1dTpPortInFrames;
		
		snprintf(port, sizeof(port), SYSFS_CLASS_NET "/%s/statistics/rx_packets", namelist[count]->d_name);
		if ((rx_packets = sysfs_open_attribute(port)) == NULL) {
			sysfs_close_attribute(rx_packets);
			snmp_log(LOG_ERR,
				 "could not open rx_packets in sysfs for bridge %s, port %s\n",
				 bridge_name, namelist[count]->d_name);
			return SNMP_ERR_GENERR;
		}

		if (sysfs_read_attribute(rx_packets) == -1) {
			snmp_log(LOG_ERR,
				 "could not read rx_packets in sysfs for bridge %s, port %s\n",
				 bridge_name, namelist[count]->d_name);
			return SNMP_ERR_GENERR;	
		}
		
		sscanf(rx_packets->value, "%u", &dot1dTpPortInFrames);
		sysfs_close_attribute(rx_packets);
		rowreq_ctx->data.dot1dTpPortInFrames = dot1dTpPortInFrames;
    
		/*
		 * setup/save data for dot1dTpPortOutFrames
		 * dot1dTpPortOutFrames(4)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
		 */
		/** no mapping */
		struct sysfs_attribute *tx_packets;
		unsigned long dot1dTpPortOutFrames;
		
		snprintf(port, sizeof(port), SYSFS_CLASS_NET "/%s/statistics/tx_packets", namelist[count]->d_name);
		if ((tx_packets = sysfs_open_attribute(port)) == NULL) {
			sysfs_close_attribute(tx_packets);
			snmp_log(LOG_ERR,
				 "could not open tx_packets in sysfs for bridge %s, port %s\n",
				 bridge_name, namelist[count]->d_name);
			return SNMP_ERR_GENERR;
		}

		if (sysfs_read_attribute(tx_packets) == -1) {
			snmp_log(LOG_ERR,
				 "could not read tx_packets in sysfs for bridge %s, port %s\n",
				 bridge_name, namelist[count]->d_name);
			return SNMP_ERR_GENERR;	
		}
		
		sscanf(tx_packets->value, "%u", &dot1dTpPortOutFrames);
		sysfs_close_attribute(tx_packets);
		rowreq_ctx->data.dot1dTpPortOutFrames = dot1dTpPortOutFrames;
    
		/*
		 * setup/save data for dot1dTpPortInDiscards
		 * dot1dTpPortInDiscards(5)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
		 */
		/** no mapping */
		struct sysfs_attribute *rx_dropped;
		unsigned long dot1dTpPortInDiscards;
		
		snprintf(port, sizeof(port), SYSFS_CLASS_NET "/%s/statistics/rx_dropped", namelist[count]->d_name);
		if ((rx_dropped = sysfs_open_attribute(port)) == NULL) {
			sysfs_close_attribute(rx_dropped);
			snmp_log(LOG_ERR,
				 "could not open rx_dropped in sysfs for bridge %s, port %s\n",
				 bridge_name, namelist[count]->d_name);
			return SNMP_ERR_GENERR;
		}

		if (sysfs_read_attribute(rx_dropped) == -1) {
			snmp_log(LOG_ERR,
				 "could not read rx_dropped in sysfs for bridge %s, port %s\n",
				 bridge_name, namelist[count]->d_name);
			return SNMP_ERR_GENERR;
		}
		
		sscanf(rx_packets->value, "%u", &dot1dTpPortInDiscards);
		sysfs_close_attribute(rx_dropped);
		rowreq_ctx->data.dot1dTpPortInDiscards = dot1dTpPortInDiscards;
    
        
		/*
		 * insert into table container
		 */
		CONTAINER_INSERT(container, rowreq_ctx);
	}

	DEBUGMSGT(("verbose:dot1dTpPortTable:dot1dTpPortTable_container_load",
		   "inserted %d records\n", count));

	return MFD_SUCCESS;
} /* dot1dTpPortTable_container_load */

/**
 * container clean up
 *
 * @param container container with all current items
 *
 *  This optional callback is called prior to all
 *  item's being removed from the container. If you
 *  need to do any processing before that, do it here.
 *
 * @note
 *  The MFD helper will take care of releasing all the row contexts.
 *
 */
void
dot1dTpPortTable_container_free(netsnmp_container *container)
{
    DEBUGMSGTL(("verbose:dot1dTpPortTable:dot1dTpPortTable_container_free","called\n"));

    /*
     * TODO:380:M: Free dot1dTpPortTable container data.
     */
} /* dot1dTpPortTable_container_free */

/**
 * prepare row for processing.
 *
 *  When the agent has located the row for a request, this function is
 *  called to prepare the row for processing. If you fully populated
 *  the data context during the index setup phase, you may not need to
 *  do anything.
 *
 * @param rowreq_ctx pointer to a context.
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 */
int
dot1dTpPortTable_row_prep( dot1dTpPortTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:dot1dTpPortTable:dot1dTpPortTable_row_prep","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:390:o: Prepare row for request.
     * If populating row data was delayed, this is the place to
     * fill in the row for this request.
     */

    return MFD_SUCCESS;
} /* dot1dTpPortTable_row_prep */

/** @} */
