/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.20 $ of : mfd-data-get.m2c,v $ 
 *
 * $Id:$
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "dot1dTpPortTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement dot1dTpPortTable get routines.
 * TODO:240:M: Implement dot1dTpPortTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot1dTpPortTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * BRIDGE-MIB::dot1dTpPortTable is subid 4 of dot1dTp.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.17.4.4, length: 9
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement dot1dTpPortTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param dot1dTpPort_val
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
dot1dTpPortTable_indexes_set_tbl_idx(dot1dTpPortTable_mib_index *tbl_idx, long dot1dTpPort_val)
{
    DEBUGMSGTL(("verbose:dot1dTpPortTable:dot1dTpPortTable_indexes_set_tbl_idx","called\n"));

    /* dot1dTpPort(1)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/R/d/h */
    tbl_idx->dot1dTpPort = dot1dTpPort_val;
    

    return MFD_SUCCESS;
} /* dot1dTpPortTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
dot1dTpPortTable_indexes_set(dot1dTpPortTable_rowreq_ctx *rowreq_ctx, long dot1dTpPort_val)
{
    DEBUGMSGTL(("verbose:dot1dTpPortTable:dot1dTpPortTable_indexes_set","called\n"));

    if(MFD_SUCCESS != dot1dTpPortTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx, dot1dTpPort_val))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != dot1dTpPortTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* dot1dTpPortTable_indexes_set */


/*---------------------------------------------------------------------
 * BRIDGE-MIB::dot1dTpPortEntry.dot1dTpPortMaxInfo
 * dot1dTpPortMaxInfo is subid 2 of dot1dTpPortEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.2.1.17.4.4.1.2
 * Description:
The maximum size of the INFO (non-MAC) field that

        this port will receive or transmit.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the dot1dTpPortMaxInfo data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param dot1dTpPortMaxInfo_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
dot1dTpPortMaxInfo_get( dot1dTpPortTable_rowreq_ctx *rowreq_ctx, long * dot1dTpPortMaxInfo_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != dot1dTpPortMaxInfo_val_ptr );


    DEBUGMSGTL(("verbose:dot1dTpPortTable:dot1dTpPortMaxInfo_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the dot1dTpPortMaxInfo data.
 * copy (* dot1dTpPortMaxInfo_val_ptr ) from rowreq_ctx->data
 */
    (* dot1dTpPortMaxInfo_val_ptr ) = rowreq_ctx->data.dot1dTpPortMaxInfo;

    return MFD_SUCCESS;
} /* dot1dTpPortMaxInfo_get */

/*---------------------------------------------------------------------
 * BRIDGE-MIB::dot1dTpPortEntry.dot1dTpPortInFrames
 * dot1dTpPortInFrames is subid 3 of dot1dTpPortEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.2.1.17.4.4.1.3
 * Description:
The number of frames that have been received by this
        port from its segment.  Note that a frame received on the
        interface corresponding to this port is only counted by
        this object if and only if it is for a protocol being
        processed by the local bridging function, including
        bridge management frames.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is COUNTER (based on perltype COUNTER)
 * The net-snmp type is ASN_COUNTER. The C type decl is u_long (u_long)
 */
/**
 * Extract the current value of the dot1dTpPortInFrames data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param dot1dTpPortInFrames_val_ptr
 *        Pointer to storage for a u_long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
dot1dTpPortInFrames_get( dot1dTpPortTable_rowreq_ctx *rowreq_ctx, u_long * dot1dTpPortInFrames_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != dot1dTpPortInFrames_val_ptr );


    DEBUGMSGTL(("verbose:dot1dTpPortTable:dot1dTpPortInFrames_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the dot1dTpPortInFrames data.
 * copy (* dot1dTpPortInFrames_val_ptr ) from rowreq_ctx->data
 */
    (* dot1dTpPortInFrames_val_ptr ) = rowreq_ctx->data.dot1dTpPortInFrames;

    return MFD_SUCCESS;
} /* dot1dTpPortInFrames_get */

/*---------------------------------------------------------------------
 * BRIDGE-MIB::dot1dTpPortEntry.dot1dTpPortOutFrames
 * dot1dTpPortOutFrames is subid 4 of dot1dTpPortEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.2.1.17.4.4.1.4
 * Description:
The number of frames that have been transmitted by this
        port to its segment.  Note that a frame transmitted on
        the interface corresponding to this port is only counted
        by this object if and only if it is for a protocol being
        processed by the local bridging function, including
        bridge management frames.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is COUNTER (based on perltype COUNTER)
 * The net-snmp type is ASN_COUNTER. The C type decl is u_long (u_long)
 */
/**
 * Extract the current value of the dot1dTpPortOutFrames data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param dot1dTpPortOutFrames_val_ptr
 *        Pointer to storage for a u_long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
dot1dTpPortOutFrames_get( dot1dTpPortTable_rowreq_ctx *rowreq_ctx, u_long * dot1dTpPortOutFrames_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != dot1dTpPortOutFrames_val_ptr );


    DEBUGMSGTL(("verbose:dot1dTpPortTable:dot1dTpPortOutFrames_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the dot1dTpPortOutFrames data.
 * copy (* dot1dTpPortOutFrames_val_ptr ) from rowreq_ctx->data
 */
    (* dot1dTpPortOutFrames_val_ptr ) = rowreq_ctx->data.dot1dTpPortOutFrames;

    return MFD_SUCCESS;
} /* dot1dTpPortOutFrames_get */

/*---------------------------------------------------------------------
 * BRIDGE-MIB::dot1dTpPortEntry.dot1dTpPortInDiscards
 * dot1dTpPortInDiscards is subid 5 of dot1dTpPortEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.2.1.17.4.4.1.5
 * Description:
Count of received valid frames that were discarded
        (i.e., filtered) by the Forwarding Process.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is COUNTER (based on perltype COUNTER)
 * The net-snmp type is ASN_COUNTER. The C type decl is u_long (u_long)
 */
/**
 * Extract the current value of the dot1dTpPortInDiscards data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param dot1dTpPortInDiscards_val_ptr
 *        Pointer to storage for a u_long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
dot1dTpPortInDiscards_get( dot1dTpPortTable_rowreq_ctx *rowreq_ctx, u_long * dot1dTpPortInDiscards_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != dot1dTpPortInDiscards_val_ptr );


    DEBUGMSGTL(("verbose:dot1dTpPortTable:dot1dTpPortInDiscards_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the dot1dTpPortInDiscards data.
 * copy (* dot1dTpPortInDiscards_val_ptr ) from rowreq_ctx->data
 */
    (* dot1dTpPortInDiscards_val_ptr ) = rowreq_ctx->data.dot1dTpPortInDiscards;

    return MFD_SUCCESS;
} /* dot1dTpPortInDiscards_get */



/** @} */
