/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.18 $ of : mfd-data-access.m2c,v $
 *
 * $Id:$
 */
#ifndef DOT1DTPPORTTABLE_DATA_ACCESS_H
#define DOT1DTPPORTTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot1dTpPortTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * BRIDGE-MIB::dot1dTpPortTable is subid 4 of dot1dTp.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.17.4.4, length: 9
*/


    int dot1dTpPortTable_init_data(dot1dTpPortTable_registration * dot1dTpPortTable_reg);


    /*
     * TODO:180:o: Review dot1dTpPortTable cache timeout.
     * The number of seconds before the cache times out
     */
#define DOT1DTPPORTTABLE_CACHE_TIMEOUT   60

void dot1dTpPortTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache);
void dot1dTpPortTable_container_shutdown(netsnmp_container *container_ptr);

int dot1dTpPortTable_container_load(netsnmp_container *container);
void dot1dTpPortTable_container_free(netsnmp_container *container);

int dot1dTpPortTable_cache_load(netsnmp_container *container);
void dot1dTpPortTable_cache_free(netsnmp_container *container);

    int dot1dTpPortTable_row_prep( dot1dTpPortTable_rowreq_ctx *rowreq_ctx);



#ifdef __cplusplus
}
#endif

#endif /* DOT1DTPPORTTABLE_DATA_ACCESS_H */
