/*
 * Note: this file originally auto-generated by mib2c using
 *  : generic-table-oids.m2c,v 1.14 2005/09/27 15:56:08 rstory Exp $
 *
 * $Id:$
 */
#ifndef DOT1DTPPORTTABLE_OIDS_H
#define DOT1DTPPORTTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table dot1dTpPortTable */
#define DOT1DTPPORTTABLE_OID              1,3,6,1,2,1,17,4,4

#define COLUMN_DOT1DTPPORT         1
    
#define COLUMN_DOT1DTPPORTMAXINFO         2
    
#define COLUMN_DOT1DTPPORTINFRAMES         3
    
#define COLUMN_DOT1DTPPORTOUTFRAMES         4
    
#define COLUMN_DOT1DTPPORTINDISCARDS         5
    

#define DOT1DTPPORTTABLE_MIN_COL   COLUMN_DOT1DTPPORT
#define DOT1DTPPORTTABLE_MAX_COL   COLUMN_DOT1DTPPORTINDISCARDS
    


#ifdef __cplusplus
}
#endif

#endif /* DOT1DTPPORTTABLE_OIDS_H */
