/*
 * Note: this file originally auto-generated by mib2c using
 *  : generic-table-oids.m2c,v 1.14 2005/09/27 15:56:08 rstory Exp $
 *
 * $Id:$
 */
#ifndef DOT1DTPFDBTABLE_OIDS_H
#define DOT1DTPFDBTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table dot1dTpFdbTable */
#define DOT1DTPFDBTABLE_OID		1,3,6,1,2,1,17,4,3

#define COLUMN_DOT1DTPFDBADDRESS	1
    
#define COLUMN_DOT1DTPFDBPORT		2
    
#define COLUMN_DOT1DTPFDBSTATUS		3
    

#define DOT1DTPFDBTABLE_MIN_COL	COLUMN_DOT1DTPFDBADDRESS
#define DOT1DTPFDBTABLE_MAX_COL	COLUMN_DOT1DTPFDBSTATUS
    


#ifdef __cplusplus
}
#endif

#endif /* DOT1DTPFDBTABLE_OIDS_H */
