/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.18 $ of : mfd-data-access.m2c,v $ 
 *
 * $Id:$
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "ctl_functions.h"

/* include our parent header */
#include "dot1dTpFdbTable.h"

#include "dot1dTpFdbTable_data_access.h"

/** @ingroup interface
 * @addtogroup data_access data_access: Routines to access data
 *
 * These routines are used to locate the data used to satisfy
 * requests.
 * 
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot1dTpFdbTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * BRIDGE-MIB::dot1dTpFdbTable is subid 3 of dot1dTp.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.17.4.3, length: 9
 */

/**
 * initialization for dot1dTpFdbTable data access
 *
 * This function is called during startup to allow you to
 * allocate any resources you need for the data table.
 *
 * @param dot1dTpFdbTable_reg
 *        Pointer to dot1dTpFdbTable_registration
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : unrecoverable error.
 */
int dot1dTpFdbTable_init_data(dot1dTpFdbTable_registration *dot1dTpFdbTable_reg)
{
	DEBUGMSGTL(("verbose:dot1dTpFdbTable:dot1dTpFdbTable_init_data","called\n"));

	/*
	 * TODO:303:o: Initialize dot1dTpFdbTable data.
	 */

	return MFD_SUCCESS;
} /* dot1dTpFdbTable_init_data */

/**
 * container overview
 *
 */

/**
 * container initialization
 *
 * @param container_ptr_ptr A pointer to a container pointer. If you
 *        create a custom container, use this parameter to return it
 *        to the MFD helper. If set to NULL, the MFD helper will
 *        allocate a container for you.
 * @param  cache A pointer to a cache structure. You can set the timeout
 *         and other cache flags using this pointer.
 *
 *  This function is called at startup to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases. If no custom
 *  container is allocated, the MFD code will create one for your.
 *
 *  This is also the place to set up cache behavior. The default, to
 *  simply set the cache timeout, will work well with the default
 *  container. If you are using a custom container, you may want to
 *  look at the cache helper documentation to see if there are any
 *  flags you want to set.
 *
 * @remark
 *  This would also be a good place to do any initialization needed
 *  for you data source. For example, opening a connection to another
 *  process that will supply the data, opening a database, etc.
 */
void dot1dTpFdbTable_container_init(netsnmp_container **container_ptr_ptr,
	netsnmp_cache *cache)
{
	DEBUGMSGTL(("verbose:dot1dTpFdbTable:dot1dTpFdbTable_container_init","called\n"));

	if (NULL == container_ptr_ptr) {
		snmp_log(LOG_ERR,"bad container param to dot1dTpFdbTable_container_init\n");
		return;
	}

	/*
	 * For advanced users, you can use a custom container. If you
	 * do not create one, one will be created for you.
	 */
	*container_ptr_ptr = NULL;

	if (NULL == cache) {
		snmp_log(LOG_ERR,"bad cache param to dot1dTpFdbTable_container_init\n");
		return;
	}

	/*
	 * TODO:345:A: Set up dot1dTpFdbTable cache properties.
	 *
	 * Also for advanced users, you can set parameters for the
	 * cache. Do not change the magic pointer, as it is used
	 * by the MFD helper. To completely disable caching, set
	 * cache->enabled to 0.
	 */
	cache->timeout = DOT1DTPFDBTABLE_CACHE_TIMEOUT; /* seconds */
} /* dot1dTpFdbTable_container_init */

/**
 * container shutdown
 *
 * @param container_ptr A pointer to the container.
 *
 *  This function is called at shutdown to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases.
 *
 *  This function is called before dot1dTpFdbTable_container_free().
 *
 * @remark
 *  This would also be a good place to do any cleanup needed
 *  for you data source. For example, closing a connection to another
 *  process that supplied the data, closing a database, etc.
 */
void dot1dTpFdbTable_container_shutdown(netsnmp_container *container_ptr)
{
	DEBUGMSGTL(("verbose:dot1dTpFdbTable:dot1dTpFdbTable_container_shutdown","called\n"));

	if (NULL == container_ptr) {
		snmp_log(LOG_ERR,"bad params to dot1dTpFdbTable_container_shutdown\n");
		return;
	}

} /* dot1dTpFdbTable_container_shutdown */

/**
 * load initial data
 *
 * TODO:350:M: Implement dot1dTpFdbTable data load
 * This function will also be called by the cache helper to load
 * the container again (after the container free function has been
 * called to free the previous contents).
 *
 * @param container container to which items should be inserted
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_RESOURCE_UNAVAILABLE : Can't access data source
 * @retval MFD_ERROR                : other error.
 *
 *  This function is called to load the index(es) (and data, optionally)
 *  for the every row in the data set.
 *
 * @remark
 *  While loading the data, the only important thing is the indexes.
 *  If access to your data is cheap/fast (e.g. you have a pointer to a
 *  structure in memory), it would make sense to update the data here.
 *  If, however, the accessing the data invovles more work (e.g. parsing
 *  some other existing data, or peforming calculations to derive the data),
 *  then you can limit yourself to setting the indexes and saving any
 *  information you will need later. Then use the saved information in
 *  dot1dTpFdbTable_row_prep() for populating data.
 *
 * @note
 *  If you need consistency between rows (like you want statistics
 *  for each row to be from the same time frame), you should set all
 *  data here.
 *
 */
int dot1dTpFdbTable_container_load(netsnmp_container *container)
{
	dot1dTpFdbTable_rowreq_ctx *rowreq_ctx;
	size_t count = 0;

	char path[SYSFS_PATH_MAX];
	struct sysfs_attribute *brforward;
	
	snprintf(path, sizeof(path), SYSFS_CLASS_NET "/%s/brforward", bridge_name);
	if ((brforward = sysfs_open_attribute(path)) == NULL) {
		sysfs_close_attribute(brforward);
		snmp_log(LOG_ERR,
			 "could not open fdb table in sysfs for bridge %s\n",
			 bridge_name);
		return SNMP_ERR_GENERR;
	}

	if (sysfs_read_attribute(brforward) == -1) {
		snmp_log(LOG_ERR,
			 "could not read fdb table in sysfs for bridge %s\n",
			 bridge_name);
		return SNMP_ERR_GENERR;	
	}

	/* Grab all of the current inteface mac addresses */
	char port[SYSFS_PATH_MAX];
	struct dirent **namelist;
	int interface_count = 0;
	int interface = 0;

	snprintf(port, sizeof(port), SYSFS_CLASS_NET "/%s/brif", bridge_name);
	interface_count = scandir(port, &namelist, not_dot_dotdot, alphasort) + 1;
	if (interface_count < 0) {
		snmp_log(LOG_ERR,
			"Error getting list of all ports of bridge %s\n",
			bridge_name);
		return SNMP_ERR_GENERR;
	}
	
	char **bridge_macs = (char **)malloc(interface_count * sizeof(char **));
	struct sysfs_attribute *mac;
	
	/* Get the core switch mac address */
	snprintf(path, sizeof(path), SYSFS_CLASS_NET "/%s/address", bridge_name);
	if ((mac = sysfs_open_attribute(path)) == NULL) {
		sysfs_close_attribute(mac);
		snmp_log(LOG_ERR,
			"could not open mac address in sysfs for bridge %s\n",
			bridge_name);
		return SNMP_ERR_GENERR;
	}
	
	if (sysfs_read_attribute(mac) == -1) {
		snmp_log(LOG_ERR,
			"could not read mac address in sysfs for bridge %s\n",
			bridge_name);
		return SNMP_ERR_GENERR;	
	}
	bridge_macs[0] = (char *)malloc(6);
	sscanf(mac->value, "%02x:%02x:%02x:%02x:%02x:%02x", &bridge_macs[0][0],
							    &bridge_macs[0][1],
							    &bridge_macs[0][2],
							    &bridge_macs[0][3],
							    &bridge_macs[0][4],
							    &bridge_macs[0][5]);
	sysfs_close_attribute(mac);

	/* Get the rest of the switch mac addresses */
	for (interface = 1; interface < interface_count; interface++) {
		snprintf(path, sizeof(path), SYSFS_CLASS_NET "/%s/address", namelist[interface - 1]->d_name);
		if ((mac = sysfs_open_attribute(path)) == NULL) {
			sysfs_close_attribute(mac);
			snmp_log(LOG_ERR,
				"could not open mac address in sysfs for bridge %s, interface %s\n",
				bridge_name, namelist[interface]->d_name);
			return SNMP_ERR_GENERR;
		}
		
		if (sysfs_read_attribute(mac) == -1) {
			snmp_log(LOG_ERR,
				"could not read mac address in sysfs for bridge %s, interface %s\n",
				bridge_name, namelist[interface]->d_name);
			return SNMP_ERR_GENERR;	
		}
		
		bridge_macs[interface] = (char *)malloc(6);
		sscanf(mac->value, "%02x:%02x:%02x:%02x:%02x:%02x", &bridge_macs[interface][0],
								    &bridge_macs[interface][1],
								    &bridge_macs[interface][2],
								    &bridge_macs[interface][3],
								    &bridge_macs[interface][4],
								    &bridge_macs[interface][5]);
		sysfs_close_attribute(mac);
	}
	
	/*
	 * temporary storage for index values
	 */
	/*
	 * dot1dTpFdbAddress(1)/MacAddress/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
	 */
	char dot1dTpFdbAddress[6];
	int dot1dTpFdbAddress_len = sizeof(dot1dTpFdbAddress);

	DEBUGMSGTL(("verbose:dot1dTpFdbTable:dot1dTpFdbTable_container_load","called\n"));

	/*
	 * TODO:351:M: |-> Load/update data in the dot1dTpFdbTable container.
	 * loop over your dot1dTpFdbTable data, allocate a rowreq context,
	 * set the index(es) [and data, optionally] and insert into
	 * the container.
	 */
	for (count = 0; count < brforward->len / sizeof(struct __fdb_entry); count++) {
		memcpy(dot1dTpFdbAddress,(((struct __fdb_entry *)(brforward->value))[count]).mac_addr, dot1dTpFdbAddress_len);
		
		/*
		 * TODO:352:M: |   |-> set indexes in new dot1dTpFdbTable rowreq context.
		 * data context will be set from the param (unless NULL,
		 *      in which case a new data context will be allocated)
		 */
		rowreq_ctx = dot1dTpFdbTable_allocate_rowreq_ctx(NULL);
		if (NULL == rowreq_ctx) {
			sysfs_close_attribute(brforward);
			snmp_log(LOG_ERR, "memory allocation failed\n");
			return MFD_RESOURCE_UNAVAILABLE;
		}
		if (MFD_SUCCESS !=
			dot1dTpFdbTable_indexes_set(rowreq_ctx, dot1dTpFdbAddress, dot1dTpFdbAddress_len)) {
			snmp_log(LOG_ERR,"error setting index while loading "
				"dot1dTpFdbTable data.\n");
			dot1dTpFdbTable_release_rowreq_ctx(rowreq_ctx);
			continue;
		}

		/*
		 * TODO:352:r: |   |-> populate dot1dTpFdbTable data context.
		 * Populate data context here. (optionally, delay until row prep)
		 */
		/*
		 * TRANSIENT or semi-TRANSIENT data:
		 * copy data or save any info needed to do it in row_prep.
		 */
		/*
		 * setup/save data for dot1dTpFdbPort
		 * dot1dTpFdbPort(2)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
		 */
		/** no mapping */
		rowreq_ctx->data.dot1dTpFdbPort = (((struct __fdb_entry *)(brforward->value))[count]).port_no;

		/*
		 * setup/save data for dot1dTpFdbStatus
		 * dot1dTpFdbStatus(3)/INTEGER/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h
		 */
		/** no mapping */
		rowreq_ctx->data.dot1dTpFdbStatus = DOT1DTPFDBSTATUS_LEARNED;
		for (interface = 0; interface < interface_count; interface++) {
			if (dot1dTpFdbAddress[0] == bridge_macs[interface][0] &&
			    dot1dTpFdbAddress[1] == bridge_macs[interface][1] &&
			    dot1dTpFdbAddress[2] == bridge_macs[interface][2] &&
			    dot1dTpFdbAddress[3] == bridge_macs[interface][3] &&
			    dot1dTpFdbAddress[4] == bridge_macs[interface][4] &&
			    dot1dTpFdbAddress[5] == bridge_macs[interface][5]) {
				rowreq_ctx->data.dot1dTpFdbStatus = DOT1DTPFDBSTATUS_SELF;
			}
		}

		/*
		 * insert into table container
		 */
		CONTAINER_INSERT(container, rowreq_ctx);
	}

	DEBUGMSGT(("verbose:dot1dTpFdbTable:dot1dTpFdbTable_container_load",
			"inserted %d records\n", count));

	for (interface = 0; interface < interface_count; interface++) {
		free(bridge_macs[interface]);
	}
	free(bridge_macs);

	sysfs_close_attribute(brforward);
	return MFD_SUCCESS;
} /* dot1dTpFdbTable_container_load */

/**
 * container clean up
 *
 * @param container container with all current items
 *
 *  This optional callback is called prior to all
 *  item's being removed from the container. If you
 *  need to do any processing before that, do it here.
 *
 * @note
 *  The MFD helper will take care of releasing all the row contexts.
 *
 */
void dot1dTpFdbTable_container_free(netsnmp_container *container)
{
	DEBUGMSGTL(("verbose:dot1dTpFdbTable:dot1dTpFdbTable_container_free","called\n"));

	/*
	 * TODO:380:M: Free dot1dTpFdbTable container data.
	 */
} /* dot1dTpFdbTable_container_free */

/**
 * prepare row for processing.
 *
 *  When the agent has located the row for a request, this function is
 *  called to prepare the row for processing. If you fully populated
 *  the data context during the index setup phase, you may not need to
 *  do anything.
 *
 * @param rowreq_ctx pointer to a context.
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 */
int dot1dTpFdbTable_row_prep(dot1dTpFdbTable_rowreq_ctx *rowreq_ctx)
{
	DEBUGMSGTL(("verbose:dot1dTpFdbTable:dot1dTpFdbTable_row_prep","called\n"));

	netsnmp_assert(NULL != rowreq_ctx);

	/*
	 * TODO:390:o: Prepare row for request.
	 * If populating row data was delayed, this is the place to
	 * fill in the row for this request.
	 */

	return MFD_SUCCESS;
} /* dot1dTpFdbTable_row_prep */

/** @} */
