/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.20 $ of : mfd-data-get.m2c,v $ 
 *
 * $Id:$
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "dot1dStpExtPortTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement dot1dStpExtPortTable get routines.
 * TODO:240:M: Implement dot1dStpExtPortTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot1dStpExtPortTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * RSTP-MIB::dot1dStpExtPortTable is subid 19 of dot1dStp.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.17.2.19, length: 9
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement dot1dStpExtPortTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param dot1dStpPort_val
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
dot1dStpExtPortTable_indexes_set_tbl_idx(dot1dStpExtPortTable_mib_index *tbl_idx, long dot1dStpPort_val)
{
    DEBUGMSGTL(("verbose:dot1dStpExtPortTable:dot1dStpExtPortTable_indexes_set_tbl_idx","called\n"));

    /* dot1dStpPort(1)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/R/d/h */
    tbl_idx->dot1dStpPort = dot1dStpPort_val;
    

    return MFD_SUCCESS;
} /* dot1dStpExtPortTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
dot1dStpExtPortTable_indexes_set(dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx, long dot1dStpPort_val)
{
    DEBUGMSGTL(("verbose:dot1dStpExtPortTable:dot1dStpExtPortTable_indexes_set","called\n"));

    if(MFD_SUCCESS != dot1dStpExtPortTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , dot1dStpPort_val
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != dot1dStpExtPortTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* dot1dStpExtPortTable_indexes_set */


/*---------------------------------------------------------------------
 * RSTP-MIB::dot1dStpExtPortEntry.dot1dStpPortProtocolMigration
 * dot1dStpPortProtocolMigration is subid 1 of dot1dStpExtPortEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.2.1.17.2.19.1.1
 * Description:
When operating in RSTP (version 2) mode, writing true(1)
         to this object forces this port to transmit RSTP BPDUs.
         Any other operation on this object has no effect and
         it always returns false(2) when read.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the dot1dStpPortProtocolMigration data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param dot1dStpPortProtocolMigration_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
dot1dStpPortProtocolMigration_get( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx, u_long * dot1dStpPortProtocolMigration_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != dot1dStpPortProtocolMigration_val_ptr );


    DEBUGMSGTL(("verbose:dot1dStpExtPortTable:dot1dStpPortProtocolMigration_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the dot1dStpPortProtocolMigration data.
 * copy (* dot1dStpPortProtocolMigration_val_ptr ) from rowreq_ctx->data
 */
    (* dot1dStpPortProtocolMigration_val_ptr ) = rowreq_ctx->data.dot1dStpPortProtocolMigration;

    return MFD_SUCCESS;
} /* dot1dStpPortProtocolMigration_get */

/*---------------------------------------------------------------------
 * RSTP-MIB::dot1dStpExtPortEntry.dot1dStpPortAdminEdgePort
 * dot1dStpPortAdminEdgePort is subid 2 of dot1dStpExtPortEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.2.1.17.2.19.1.2
 * Description:
The administrative value of the Edge Port parameter.  A
         value of true(1) indicates that this port should be
         assumed as an edge-port, and a value of false(2) indicates
         that this port should be assumed as a non-edge-port.

         Setting this object will also cause the corresponding
         instance of dot1dStpPortOperEdgePort to change to the
         same value.  Note that even when this object's value
         is true, the value of the corresponding instance of
         dot1dStpPortOperEdgePort can be false if a BPDU has
         been received.

         The value of this object MUST be retained across
         reinitializations of the management system.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the dot1dStpPortAdminEdgePort data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param dot1dStpPortAdminEdgePort_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
dot1dStpPortAdminEdgePort_get( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx, u_long * dot1dStpPortAdminEdgePort_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != dot1dStpPortAdminEdgePort_val_ptr );


    DEBUGMSGTL(("verbose:dot1dStpExtPortTable:dot1dStpPortAdminEdgePort_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the dot1dStpPortAdminEdgePort data.
 * copy (* dot1dStpPortAdminEdgePort_val_ptr ) from rowreq_ctx->data
 */
    (* dot1dStpPortAdminEdgePort_val_ptr ) = rowreq_ctx->data.dot1dStpPortAdminEdgePort;

    return MFD_SUCCESS;
} /* dot1dStpPortAdminEdgePort_get */

/*---------------------------------------------------------------------
 * RSTP-MIB::dot1dStpExtPortEntry.dot1dStpPortOperEdgePort
 * dot1dStpPortOperEdgePort is subid 3 of dot1dStpExtPortEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.2.1.17.2.19.1.3
 * Description:
The operational value of the Edge Port parameter.  The
         object is initialized to the value of the corresponding
         instance of dot1dStpPortAdminEdgePort.  When the
         corresponding instance of dot1dStpPortAdminEdgePort is
         set, this object will be changed as well.  This object
         will also be changed to false on reception of a BPDU.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the dot1dStpPortOperEdgePort data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param dot1dStpPortOperEdgePort_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
dot1dStpPortOperEdgePort_get( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx, u_long * dot1dStpPortOperEdgePort_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != dot1dStpPortOperEdgePort_val_ptr );


    DEBUGMSGTL(("verbose:dot1dStpExtPortTable:dot1dStpPortOperEdgePort_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the dot1dStpPortOperEdgePort data.
 * copy (* dot1dStpPortOperEdgePort_val_ptr ) from rowreq_ctx->data
 */
    (* dot1dStpPortOperEdgePort_val_ptr ) = rowreq_ctx->data.dot1dStpPortOperEdgePort;

    return MFD_SUCCESS;
} /* dot1dStpPortOperEdgePort_get */

/*---------------------------------------------------------------------
 * RSTP-MIB::dot1dStpExtPortEntry.dot1dStpPortAdminPointToPoint
 * dot1dStpPortAdminPointToPoint is subid 4 of dot1dStpExtPortEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.2.1.17.2.19.1.4
 * Description:
The administrative point-to-point status of the LAN segment
         attached to this port, using the enumeration values of the
         IEEE 802.1w clause.  A value of forceTrue(0) indicates
         that this port should always be treated as if it is
         connected to a point-to-point link.  A value of
         forceFalse(1) indicates that this port should be treated as
         having a shared media connection.  A value of auto(2)
         indicates that this port is considered to have a
         point-to-point link if it is an Aggregator and all of its
         members are aggregatable, or if the MAC entity
         is configured for full duplex operation, either through
         auto-negotiation or by management means.  Manipulating this
         object changes the underlying adminPortToPortMAC.

         The value of this object MUST be retained across
         reinitializations of the management system.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 3/8. Values:  forceTrue(0), forceFalse(1), auto(2)
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the dot1dStpPortAdminPointToPoint data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param dot1dStpPortAdminPointToPoint_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
dot1dStpPortAdminPointToPoint_get( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx, u_long * dot1dStpPortAdminPointToPoint_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != dot1dStpPortAdminPointToPoint_val_ptr );


    DEBUGMSGTL(("verbose:dot1dStpExtPortTable:dot1dStpPortAdminPointToPoint_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the dot1dStpPortAdminPointToPoint data.
 * copy (* dot1dStpPortAdminPointToPoint_val_ptr ) from rowreq_ctx->data
 */
    (* dot1dStpPortAdminPointToPoint_val_ptr ) = rowreq_ctx->data.dot1dStpPortAdminPointToPoint;

    return MFD_SUCCESS;
} /* dot1dStpPortAdminPointToPoint_get */

/*---------------------------------------------------------------------
 * RSTP-MIB::dot1dStpExtPortEntry.dot1dStpPortOperPointToPoint
 * dot1dStpPortOperPointToPoint is subid 5 of dot1dStpExtPortEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.2.1.17.2.19.1.5
 * Description:
The operational point-to-point status of the LAN segment
         attached to this port.  It indicates whether a port is
         considered to have a point-to-point connection.
         If adminPointToPointMAC is set to auto(2), then the value
         of operPointToPointMAC is determined in accordance with the
         specific procedures defined for the MAC entity concerned,
         as defined in IEEE 802.1w, clause 6.5.  The value is
         determined dynamically; that is, it is re-evaluated whenever
         the value of adminPointToPointMAC changes, and whenever
         the specific procedures defined for the MAC entity evaluate
         a change in its point-to-point status.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the dot1dStpPortOperPointToPoint data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param dot1dStpPortOperPointToPoint_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
dot1dStpPortOperPointToPoint_get( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx, u_long * dot1dStpPortOperPointToPoint_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != dot1dStpPortOperPointToPoint_val_ptr );


    DEBUGMSGTL(("verbose:dot1dStpExtPortTable:dot1dStpPortOperPointToPoint_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the dot1dStpPortOperPointToPoint data.
 * copy (* dot1dStpPortOperPointToPoint_val_ptr ) from rowreq_ctx->data
 */
    (* dot1dStpPortOperPointToPoint_val_ptr ) = rowreq_ctx->data.dot1dStpPortOperPointToPoint;

    return MFD_SUCCESS;
} /* dot1dStpPortOperPointToPoint_get */

/*---------------------------------------------------------------------
 * RSTP-MIB::dot1dStpExtPortEntry.dot1dStpPortAdminPathCost
 * dot1dStpPortAdminPathCost is subid 6 of dot1dStpExtPortEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.2.1.17.2.19.1.6
 * Description:
The administratively assigned value for the contribution
         of this port to the path cost of paths toward the spanning
         tree root.

         Writing a value of '0' assigns the automatically calculated
         default Path Cost value to the port.  If the default Path
         Cost is being used, this object returns '0' when read.

         This complements the object dot1dStpPortPathCost or
         dot1dStpPortPathCost32, which returns the operational value
         of the path cost.

         The value of this object MUST be retained across
         reinitializations of the management system.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   1
 *
 * Ranges:  0 - 200000000;
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the dot1dStpPortAdminPathCost data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param dot1dStpPortAdminPathCost_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
dot1dStpPortAdminPathCost_get( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx, long * dot1dStpPortAdminPathCost_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != dot1dStpPortAdminPathCost_val_ptr );


    DEBUGMSGTL(("verbose:dot1dStpExtPortTable:dot1dStpPortAdminPathCost_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the dot1dStpPortAdminPathCost data.
 * copy (* dot1dStpPortAdminPathCost_val_ptr ) from rowreq_ctx->data
 */
    (* dot1dStpPortAdminPathCost_val_ptr ) = rowreq_ctx->data.dot1dStpPortAdminPathCost;

    return MFD_SUCCESS;
} /* dot1dStpPortAdminPathCost_get */



/** @} */
