/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.19 $ of : mfd-data-set.m2c,v $ 
 *
 * $Id:$
 */
#ifndef DOT1DSTPEXTPORTTABLE_DATA_SET_H
#define DOT1DSTPEXTPORTTABLE_DATA_SET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * SET function declarations
 */

/* *********************************************************************
 * SET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot1dStpExtPortTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * RSTP-MIB::dot1dStpExtPortTable is subid 19 of dot1dStp.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.17.2.19, length: 9
*/


int dot1dStpExtPortTable_undo_setup( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx);
int dot1dStpExtPortTable_undo_cleanup( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx);
int dot1dStpExtPortTable_undo( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx);
int dot1dStpExtPortTable_commit( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx);
int dot1dStpExtPortTable_undo_commit( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx);


int dot1dStpPortProtocolMigration_check_value( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx, u_long dot1dStpPortProtocolMigration_val);
int dot1dStpPortProtocolMigration_undo_setup( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx );
int dot1dStpPortProtocolMigration_set( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx, u_long dot1dStpPortProtocolMigration_val );
int dot1dStpPortProtocolMigration_undo( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx );

int dot1dStpPortAdminEdgePort_check_value( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx, u_long dot1dStpPortAdminEdgePort_val);
int dot1dStpPortAdminEdgePort_undo_setup( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx );
int dot1dStpPortAdminEdgePort_set( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx, u_long dot1dStpPortAdminEdgePort_val );
int dot1dStpPortAdminEdgePort_undo( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx );

int dot1dStpPortOperEdgePort_check_value( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx, u_long dot1dStpPortOperEdgePort_val);
int dot1dStpPortOperEdgePort_undo_setup( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx );
int dot1dStpPortOperEdgePort_set( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx, u_long dot1dStpPortOperEdgePort_val );
int dot1dStpPortOperEdgePort_undo( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx );

int dot1dStpPortAdminPointToPoint_check_value( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx, u_long dot1dStpPortAdminPointToPoint_val);
int dot1dStpPortAdminPointToPoint_undo_setup( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx );
int dot1dStpPortAdminPointToPoint_set( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx, u_long dot1dStpPortAdminPointToPoint_val );
int dot1dStpPortAdminPointToPoint_undo( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx );

int dot1dStpPortOperPointToPoint_check_value( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx, u_long dot1dStpPortOperPointToPoint_val);
int dot1dStpPortOperPointToPoint_undo_setup( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx );
int dot1dStpPortOperPointToPoint_set( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx, u_long dot1dStpPortOperPointToPoint_val );
int dot1dStpPortOperPointToPoint_undo( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx );

int dot1dStpPortAdminPathCost_check_value( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx, long dot1dStpPortAdminPathCost_val);
int dot1dStpPortAdminPathCost_undo_setup( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx );
int dot1dStpPortAdminPathCost_set( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx, long dot1dStpPortAdminPathCost_val );
int dot1dStpPortAdminPathCost_undo( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx );


int dot1dStpExtPortTable_check_dependencies(dot1dStpExtPortTable_rowreq_ctx *ctx);


#ifdef __cplusplus
}
#endif

#endif /* DOT1DSTPEXTPORTTABLE_DATA_SET_H */
