/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.50 $ of : mfd-top.m2c,v $
 *
 * $Id:$
 */
#ifndef DOT1DSTPEXTPORTTABLE_H
#define DOT1DSTPEXTPORTTABLE_H

#ifdef __cplusplus
extern "C" {
#endif


/** @addtogroup misc misc: Miscellaneous routines
 *
 * @{
 */
#include <net-snmp/library/asn1.h>

/* other required module components */
    /* *INDENT-OFF*  */
config_add_mib(RSTP-MIB)
config_require(RSTP-MIB/dot1dStpExtPortTable/dot1dStpExtPortTable_interface)
config_require(RSTP-MIB/dot1dStpExtPortTable/dot1dStpExtPortTable_data_access)
config_require(RSTP-MIB/dot1dStpExtPortTable/dot1dStpExtPortTable_data_get)
config_require(RSTP-MIB/dot1dStpExtPortTable/dot1dStpExtPortTable_data_set)
    /* *INDENT-ON*  */

/* OID and column number definitions for dot1dStpExtPortTable */
#include "dot1dStpExtPortTable_oids.h"

/* enum definions */
#include "dot1dStpExtPortTable_enums.h"

/* *********************************************************************
 * function declarations
 */
void init_dot1dStpExtPortTable(void);
void shutdown_dot1dStpExtPortTable(void);

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot1dStpExtPortTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * RSTP-MIB::dot1dStpExtPortTable is subid 19 of dot1dStp.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.17.2.19, length: 9
*/
/* *********************************************************************
 * When you register your mib, you get to provide a generic
 * pointer that will be passed back to you for most of the
 * functions calls.
 *
 * TODO:100:r: Review all context structures
 */
    /*
     * TODO:101:o: |-> Review dot1dStpExtPortTable registration context.
     */
typedef netsnmp_data_list dot1dStpExtPortTable_registration;

/**********************************************************************/
/*
 * TODO:110:r: |-> Review dot1dStpExtPortTable data context structure.
 * This structure is used to represent the data for dot1dStpExtPortTable.
 */
/*
 * This structure contains storage for all the columns defined in the
 * dot1dStpExtPortTable.
 */
typedef struct dot1dStpExtPortTable_data_s {
    
        /*
         * dot1dStpPortProtocolMigration(1)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h
         */
   u_long   dot1dStpPortProtocolMigration;
    
        /*
         * dot1dStpPortAdminEdgePort(2)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h
         */
   u_long   dot1dStpPortAdminEdgePort;
    
        /*
         * dot1dStpPortOperEdgePort(3)/TruthValue/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h
         */
   u_long   dot1dStpPortOperEdgePort;
    
        /*
         * dot1dStpPortAdminPointToPoint(4)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h
         */
   u_long   dot1dStpPortAdminPointToPoint;
    
        /*
         * dot1dStpPortOperPointToPoint(5)/TruthValue/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h
         */
   u_long   dot1dStpPortOperPointToPoint;
    
        /*
         * dot1dStpPortAdminPathCost(6)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/R/d/h
         */
   long   dot1dStpPortAdminPathCost;
    
} dot1dStpExtPortTable_data;


/* *********************************************************************
 * TODO:115:o: |-> Review dot1dStpExtPortTable undo context.
 * We're just going to use the same data structure for our
 * undo_context. If you want to do something more efficent,
 * define your typedef here.
 */
typedef dot1dStpExtPortTable_data dot1dStpExtPortTable_undo_data;

/*
 * TODO:120:r: |-> Review dot1dStpExtPortTable mib index.
 * This structure is used to represent the index for dot1dStpExtPortTable.
 */
typedef struct dot1dStpExtPortTable_mib_index_s {

        /*
         * dot1dStpPort(1)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/R/d/h
         */
   long   dot1dStpPort;


} dot1dStpExtPortTable_mib_index;

    /*
     * TODO:121:r: |   |-> Review dot1dStpExtPortTable max index length.
     * If you KNOW that your indexes will never exceed a certain
     * length, update this macro to that length.
*/
#define MAX_dot1dStpExtPortTable_IDX_LEN     1


/* *********************************************************************
 * TODO:130:o: |-> Review dot1dStpExtPortTable Row request (rowreq) context.
 * When your functions are called, you will be passed a
 * dot1dStpExtPortTable_rowreq_ctx pointer.
 */
typedef struct dot1dStpExtPortTable_rowreq_ctx_s {

    /** this must be first for container compare to work */
    netsnmp_index        oid_idx;
    oid                  oid_tmp[MAX_dot1dStpExtPortTable_IDX_LEN];
    
    dot1dStpExtPortTable_mib_index        tbl_idx;
    
    dot1dStpExtPortTable_data              data;
    dot1dStpExtPortTable_undo_data       * undo;
    unsigned int                column_set_flags; /* flags for set columns */


    /*
     * flags per row. Currently, the first (lower) 8 bits are reserved
     * for the user. See mfd.h for other flags.
     */
    u_int                       rowreq_flags;

    /*
     * TODO:131:o: |   |-> Add useful data to dot1dStpExtPortTable rowreq context.
     */
    
    /*
     * storage for future expansion
     */
    netsnmp_data_list             *dot1dStpExtPortTable_data_list;

} dot1dStpExtPortTable_rowreq_ctx;

typedef struct dot1dStpExtPortTable_ref_rowreq_ctx_s {
    dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx;
} dot1dStpExtPortTable_ref_rowreq_ctx;

/* *********************************************************************
 * function prototypes
 */
    int dot1dStpExtPortTable_pre_request(dot1dStpExtPortTable_registration * user_context);
    int dot1dStpExtPortTable_post_request(dot1dStpExtPortTable_registration * user_context,
        int rc);

    int dot1dStpExtPortTable_rowreq_ctx_init(dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx,
                                   void *user_init_ctx);
    void dot1dStpExtPortTable_rowreq_ctx_cleanup(dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx);

    int dot1dStpExtPortTable_commit(dot1dStpExtPortTable_rowreq_ctx * rowreq_ctx);

    dot1dStpExtPortTable_rowreq_ctx *
                  dot1dStpExtPortTable_row_find_by_mib_index(dot1dStpExtPortTable_mib_index *mib_idx);

extern oid dot1dStpExtPortTable_oid[];
extern int dot1dStpExtPortTable_oid_size;


#include "dot1dStpExtPortTable_interface.h"
#include "dot1dStpExtPortTable_data_access.h"
#include "dot1dStpExtPortTable_data_get.h"
#include "dot1dStpExtPortTable_data_set.h"

/*
 * DUMMY markers, ignore
 *
 * TODO:099:x: *************************************************************
 * TODO:199:x: *************************************************************
 * TODO:299:x: *************************************************************
 * TODO:399:x: *************************************************************
 * TODO:499:x: *************************************************************
 */

#ifdef __cplusplus
}
#endif

#endif /* DOT1DSTPEXTPORTTABLE_H */
/** @} */
