/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.20 $ of : mfd-data-get.m2c,v $
 *
 * $Id:$
 *
 * @file dot1dStpExtPortTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef DOT1DSTPEXTPORTTABLE_DATA_GET_H
#define DOT1DSTPEXTPORTTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot1dStpExtPortTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * RSTP-MIB::dot1dStpExtPortTable is subid 19 of dot1dStp.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.17.2.19, length: 9
*/
    /*
     * indexes
     */

    int dot1dStpPortProtocolMigration_get( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx, u_long * dot1dStpPortProtocolMigration_val_ptr );
    int dot1dStpPortAdminEdgePort_get( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx, u_long * dot1dStpPortAdminEdgePort_val_ptr );
    int dot1dStpPortOperEdgePort_get( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx, u_long * dot1dStpPortOperEdgePort_val_ptr );
    int dot1dStpPortAdminPointToPoint_get( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx, u_long * dot1dStpPortAdminPointToPoint_val_ptr );
    int dot1dStpPortOperPointToPoint_get( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx, u_long * dot1dStpPortOperPointToPoint_val_ptr );
    int dot1dStpPortAdminPathCost_get( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx, long * dot1dStpPortAdminPathCost_val_ptr );


int dot1dStpExtPortTable_indexes_set_tbl_idx(dot1dStpExtPortTable_mib_index *tbl_idx, long dot1dStpPort_val);
int dot1dStpExtPortTable_indexes_set(dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx, long dot1dStpPort_val);




#ifdef __cplusplus
}
#endif

#endif /* DOT1DSTPEXTPORTTABLE_DATA_GET_H */
/** @} */
