/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.18 $ of : mfd-data-access.m2c,v $
 *
 * $Id:$
 */
#ifndef DOT1DSTPEXTPORTTABLE_DATA_ACCESS_H
#define DOT1DSTPEXTPORTTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot1dStpExtPortTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * RSTP-MIB::dot1dStpExtPortTable is subid 19 of dot1dStp.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.17.2.19, length: 9
*/


    int dot1dStpExtPortTable_init_data(dot1dStpExtPortTable_registration * dot1dStpExtPortTable_reg);


    /*
     * TODO:180:o: Review dot1dStpExtPortTable cache timeout.
     * The number of seconds before the cache times out
     */
#define DOT1DSTPEXTPORTTABLE_CACHE_TIMEOUT   60

void dot1dStpExtPortTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache);
void dot1dStpExtPortTable_container_shutdown(netsnmp_container *container_ptr);

int dot1dStpExtPortTable_container_load(netsnmp_container *container);
void dot1dStpExtPortTable_container_free(netsnmp_container *container);

int dot1dStpExtPortTable_cache_load(netsnmp_container *container);
void dot1dStpExtPortTable_cache_free(netsnmp_container *container);

    int dot1dStpExtPortTable_row_prep( dot1dStpExtPortTable_rowreq_ctx *rowreq_ctx);



#ifdef __cplusplus
}
#endif

#endif /* DOT1DSTPEXTPORTTABLE_DATA_ACCESS_H */
